"use client";
import {useEffect,useState} from "react";
import Sidebar from "../components/Sidebar";
import {apiFetch,getSession} from "../lib/api";
import {useRequireSession} from "../lib/useRequireSession";
import { money } from "../lib/format";


export default function CashierSessions(){
 useRequireSession();const session=getSession();const manager=["super_admin","admin","manager"].includes(session?.Role||"");
 const[rows,setRows]=useState<any[]>([]),[policies,setPolicies]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[note,setNote]=useState(""),[approved,setApproved]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{setRows(await apiFetch("/cashier-sessions"));if(manager)setPolicies(await apiFetch("/pos/discount-policies"));}catch(e:any){setMessage(e.message)}};
 useEffect(()=>{load()},[]);
 const reconcile=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);try{await apiFetch(`/cashier-sessions/${selected.id}/reconcile`,{method:"POST",body:JSON.stringify({note,approveVariance:approved})});setMessage("Cashier session reconciled and locked.");setSelected(null);setNote("");setApproved(false);await load()}catch(x:any){setMessage(x.message)}finally{setBusy(false)}};
 const savePolicy=async(row:any)=>{setBusy(true);try{await apiFetch("/pos/discount-policies",{method:"PUT",body:JSON.stringify(row)});setMessage(`${row.name} discount limits saved.`);await load()}catch(x:any){setMessage(x.message)}finally{setBusy(false)}};
 return <main className="shell"><Sidebar active="Cashier sessions"/><section className="app"><header className="topbar"><div><span className="crumb">Sales / Cashier control</span><b>Cashier management</b></div></header><div className="page cashierControl"><div className="pageHeading"><div><p>REGISTER CONTROL</p><h1>Cashier sessions & reconciliation</h1><small>Review opening cash, cash sales, refunds, counted cash and shift variances.</small></div></div>{message&&<button className="notice" onClick={()=>setMessage("")}>{message}</button>}
 <section className="cashierMetrics"><article><small>Open sessions</small><b>{rows.filter(x=>x.status==="open").length}</b></article><article><small>Awaiting reconciliation</small><b>{rows.filter(x=>x.status==="closed").length}</b></article><article><small>Total variance</small><b>{money(rows.reduce((s,x)=>s+Number(x.variance||0),0))}</b></article></section>
 <section className="workflowRecords"><header><div><h2>Register history</h2><small>{manager?"All cashiers in this workspace":"Your cashier sessions"}</small></div><span>{rows.length} sessions</span></header><div className="tableScroll"><table><thead><tr><th>Cashier / branch</th><th>Opened</th><th>Cash movement</th><th>Expected / counted</th><th>Variance</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.cashier}</b><small>{row.branch||"Unassigned"}</small></td><td>{new Date(row.openedAt).toLocaleString()}</td><td><b>{money(row.cashSales)}</b><small>Returns -{money(row.cashReturns)}</small></td><td><b>{money(row.expected)}</b><small>{row.closing==null?"Not counted":`Counted ${money(row.closing)}`}</small></td><td><b className={Number(row.variance)===0?"balancedText":"varianceText"}>{row.variance==null?"—":money(row.variance)}</b></td><td><span className={`saleStatus ${row.status}`}>{row.status}</span></td><td>{manager&&row.status==="closed"?<button className="viewInvoiceButton" onClick={()=>setSelected(row)}>Reconcile</button>:<span>{row.status==="reconciled"?"Locked":"—"}</span>}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="emptyState">No cashier sessions yet.</div>}</section>
 {manager&&<section className="workflowRecords discountPolicy"><header><div><h2>Role discount limits</h2><small>Server-enforced maximum discount percentages.</small></div></header><div className="policyGrid">{policies.map((row,index)=><article key={row.roleId}><div><b>{row.name}</b><small>{row.key.replaceAll("_"," ")}</small></div><label>Item %<input type="number" min="0" max="100" value={row.maxItemPercent} onChange={e=>setPolicies(p=>p.map((x,i)=>i===index?{...x,maxItemPercent:Number(e.target.value)}:x))}/></label><label>Invoice %<input type="number" min="0" max="100" value={row.maxInvoicePercent} onChange={e=>setPolicies(p=>p.map((x,i)=>i===index?{...x,maxInvoicePercent:Number(e.target.value)}:x))}/></label><button disabled={busy} onClick={()=>savePolicy(row)}>Save</button></article>)}</div></section>}
 </div></section>{selected&&<div className="transactionDialog"><form onSubmit={reconcile}><header><div><small>MANAGER REVIEW</small><h2>Reconcile {selected.cashier}</h2></div><button type="button" onClick={()=>setSelected(null)}>×</button></header><div className="reconcileSummary"><span>Expected<b>{money(selected.expected)}</b></span><span>Counted<b>{money(selected.closing)}</b></span><span>Variance<b>{money(selected.variance)}</b></span></div>{Number(selected.variance)!==0&&<label className="approvalCheck"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I reviewed and approve this cash variance</label>}<label className="reasonField">Reconciliation note<textarea rows={3} required={Number(selected.variance)!==0} value={note} onChange={e=>setNote(e.target.value)} placeholder="Count verification, variance reason or manager note"/></label><footer><button type="button" onClick={()=>setSelected(null)}>Cancel</button><button className="new" disabled={busy||Number(selected.variance)!==0&&(!approved||!note.trim())}>{busy?"Saving…":"Approve reconciliation"}</button></footer></form></div>}</main>
}
