"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import Sidebar from "../components/Sidebar";
import BusinessDocumentHeader from "../components/BusinessDocumentHeader";
import { apiFetch, can } from "../lib/api";
import { useRequireSession } from "../lib/useRequireSession";
import { type MoneyFigure, money, moneyFigure } from "../lib/format";

type Filters = { q: string; from: string; to: string; customerId: string; cashierId: string; paymentMethod: string; status: string; limit: string };
const initialFilters: Filters = { q: "", from: "", to: "", customerId: "", cashierId: "", paymentMethod: "", status: "", limit: "25" };

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function SalesPage() {
  useRequireSession();
  const searchParams = useSearchParams();
  const startingFilters = { ...initialFilters, status: searchParams.get("status") || "" };
  const [filters, setFilters] = useState<Filters>(startingFilters), [applied, setApplied] = useState<Filters>(startingFilters);
  const [page, setPage] = useState(1), [data, setData] = useState<any>({ rows: [], total: 0, page: 1, limit: 25, summary: {}, cashiers: [] });
  const [customers, setCustomers] = useState<any[]>([]), [loading, setLoading] = useState(true), [message, setMessage] = useState("");
  const [invoice, setInvoice] = useState<any>(null), [invoiceLoading, setInvoiceLoading] = useState(false), [returning, setReturning] = useState(false), [cancelling, setCancelling] = useState(false);

  useEffect(() => {
    const status = searchParams.get("status") || "";
    setFilters((current) => ({ ...current, status }));
    setApplied((current) => ({ ...current, status }));
    setPage(1);
  }, [searchParams]);

  const load = async () => {
    setLoading(true); setMessage("");
    try { const query = new URLSearchParams({ ...applied, page: String(page) }); Object.entries(applied).forEach(([key, value]) => { if (!value) query.delete(key); }); setData(await apiFetch(`/sales?${query}`)); }
    catch (error: any) { setMessage(error.message); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [applied, page]);
  useEffect(() => { apiFetch("/customers").then(setCustomers).catch(() => setCustomers([])); }, []);
  const set = (key: keyof Filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const apply = (event: React.FormEvent) => { event.preventDefault(); setPage(1); setApplied(filters); };
  const reset = () => { setFilters(initialFilters); setApplied(initialFilters); setPage(1); };
  const openInvoice = async (id: string) => { setInvoiceLoading(true); setMessage(""); try { setInvoice(await apiFetch(`/invoices/${id}`)); } catch (error: any) { setMessage(error.message); } finally { setInvoiceLoading(false); } };
  const refreshInvoice = async () => { if (!invoice) return; const fresh = await apiFetch(`/invoices/${invoice.id}`); setInvoice(fresh); await load(); };
  const exportCSV = () => { const rows = ["Invoice,Date,Customer,Cashier,Payment,Status,Gross,Returned,Net,Paid,Balance", ...data.rows.map((row: any) => [row.invoice, new Date(row.createdAt).toLocaleString(), row.customer, row.cashier, row.paymentMethod, row.status, row.total, row.returned, row.netTotal, row.netPaid, row.balance].map((cell) => `"${String(cell ?? "").replaceAll('"', '""')}"`).join(","))]; const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "sales.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const pages = Math.max(1, Math.ceil((data.total || 0) / Number(applied.limit || 25)));

  return <main className="shell"><Sidebar active="Sales history"/><section className="app"><header className="topbar"><div><span className="crumb">Sales / Invoice control</span><b>Sales workspace</b></div><div className="salesTopActions"><button className="ghostButton" disabled={!data.rows.length} onClick={exportCSV}>Export CSV</button><Link className="new" href="/pos">+ New sale</Link></div></header><div className="page salesWorkspace">
    <div className="pageHeading"><div><p>SALES CONTROL</p><h1>Invoices & returns</h1><small>Find an invoice, inspect every line, reprint it, or use a controlled return/cancellation workflow.</small></div></div>
    <section className="salesSummary"><Summary title="Matching sales" value={String(data.total || 0)} hint="Invoices in this result"/><Summary title="Gross value" figure={moneyFigure(data.summary?.gross)} hint="Before returns"/><Summary title="Returns" figure={moneyFigure((data.summary?.gross || 0) - (data.summary?.net || 0))} hint="Accepted return value" tone="warning"/><Summary title="Net sales" figure={moneyFigure(data.summary?.net)} hint="After returns/cancellations" tone="positive"/><Summary title="Outstanding" figure={moneyFigure(data.summary?.balance)} hint="Customer receivables"/></section>
    <form className="salesFilters" onSubmit={apply}><label className="wide">Search invoice or customer<input value={filters.q} onChange={(event) => set("q", event.target.value)} placeholder="Invoice number or customer name"/></label><label>From<input type="date" value={filters.from} onChange={(event) => set("from", event.target.value)}/></label><label>To<input type="date" value={filters.to} onChange={(event) => set("to", event.target.value)}/></label><label>Customer<select value={filters.customerId} onChange={(event) => set("customerId", event.target.value)}><option value="">All customers</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{data.canViewAll && <label>Cashier<select value={filters.cashierId} onChange={(event) => set("cashierId", event.target.value)}><option value="">All cashiers</option>{data.cashiers.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Payment<select value={filters.paymentMethod} onChange={(event) => set("paymentMethod", event.target.value)}><option value="">All methods</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="credit">Credit</option></select></label><label>Status<select value={filters.status} onChange={(event) => set("status", event.target.value)}><option value="">All statuses</option><option value="has_returns">Any returned invoice</option><option value="completed">Completed</option><option value="partial_returned">Partially returned</option><option value="returned">Fully returned</option><option value="cancelled">Cancelled</option></select></label><div className="filterActions"><button type="button" onClick={reset}>Reset</button><button className="new">Apply filters</button></div></form>
    {message && <button className="catalogMessage" onClick={() => setMessage("")}>{message}<span>×</span></button>}
    <section className="workflowRecords salesTable"><header><div><h2>Sales register</h2><small>{loading ? "Loading invoices…" : `${data.total || 0} matching invoices`}</small></div></header><div className="tableScroll"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Cashier / Branch</th><th>Payment</th><th>Net total</th><th>Paid / Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.rows.map((row: any) => <tr key={row.id}><td><b>{row.invoice}</b><small>{new Date(row.createdAt).toLocaleString()}</small></td><td><b>{row.customer}</b></td><td><b>{row.cashier}</b><small>{row.branch || "Unassigned"}</small></td><td><span className="paymentBadge">{label(row.paymentMethod)}</span></td><td><b>{money(row.netTotal)}</b>{row.returned > 0 && <small>{money(row.returned)} returned</small>}</td><td><b>{money(row.netPaid)}</b><small>{money(row.balance)} due</small></td><td><span className={`saleStatus ${row.status}`}>{label(row.status)}</span></td><td><button className="viewInvoiceButton" onClick={() => openInvoice(row.id)}>View invoice</button></td></tr>)}</tbody></table></div>{!loading && !data.rows.length && <div className="emptyState">No invoices match these filters.</div>}<footer className="expiryPagination"><label>Rows<select value={filters.limit} onChange={(event) => { set("limit", event.target.value); setApplied((current) => ({ ...current, limit: event.target.value })); setPage(1); }}><option>25</option><option>50</option><option>100</option></select></label><span>Page {page} of {pages}</span><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><button disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Next</button></footer></section>
  </div></section>{invoiceLoading && <div className="invoiceLoading">Loading invoice…</div>}{invoice && <><button className="historyBackdrop" onClick={() => setInvoice(null)}/><InvoicePanel invoice={invoice} close={() => setInvoice(null)} startReturn={() => setReturning(true)} startCancel={() => setCancelling(true)}/></>}{returning && invoice && <ReturnDialog invoice={invoice} close={() => setReturning(false)} saved={async () => { setReturning(false); await refreshInvoice(); }}/>} {cancelling && invoice && <CancelDialog invoice={invoice} close={() => setCancelling(false)} saved={async () => { setCancelling(false); await refreshInvoice(); }}/>}</main>;
}

function Summary({ title, figure, value, hint, tone = "" }: { title: string; figure?: MoneyFigure; value?: string; hint: string; tone?: string }) { return <article className={tone}><small>{title}</small>{figure ? <b className={figure.className} title={figure.title}>{figure.text}</b> : <b>{value}</b>}<span>{hint}</span></article>; }

function InvoicePanel({ invoice, close, startReturn, startCancel }: any) {
  const canReturn = can("sales_returns.add") && (invoice.status === "completed" || invoice.status === "partial_returned") && invoice.items.some((item: any) => item.returnableQuantity > 0);
  const canCancel = can("sales.cancel") && invoice.status === "completed" && invoice.returned === 0;
  return <aside className="invoicePanel"><header><div><small>INVOICE DETAIL</small><h2>{invoice.invoice}</h2></div><button onClick={close}>×</button></header><div id="invoice-print" className="invoiceDocument"><div className="invoiceIdentity"><BusinessDocumentHeader/><span className={`saleStatus ${invoice.status}`}>{label(invoice.status)}</span></div><div className="invoiceMeta"><span><small>Issued</small><b>{new Date(invoice.createdAt).toLocaleString()}</b></span><span><small>Customer</small><b>{invoice.customer}</b></span><span><small>Cashier</small><b>{invoice.cashier}</b></span><span><small>Branch</small><b>{invoice.branch || "Unassigned"}</b></span></div><table><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>{invoice.items.map((item: any) => <tr key={item.id}><td><b>{item.product}</b><small>{item.sku}</small></td><td>{item.quantity}{item.returnedQuantity > 0 && <small>{item.returnedQuantity} returned</small>}</td><td>{money(item.unitPrice)}</td><td>{money(item.total)}</td></tr>)}</tbody></table><div className="invoiceTotals"><span>Subtotal <b>{money(invoice.total + invoice.discount)}</b></span><span>Discount <b>-{money(invoice.discount)}</b></span>{invoice.returned > 0 && <span>Returns <b>-{money(invoice.returned)}</b></span>}<span className="grand">Net total <b>{money(invoice.netTotal)}</b></span><span>Net paid <b>{money(invoice.netPaid)}</b></span><span>Outstanding <b>{money(invoice.netBalance)}</b></span><span>Payment method <b>{label(invoice.paymentMethod)}</b></span></div>{invoice.cancellationReason && <div className="cancellationNote"><b>Cancellation reason</b><span>{invoice.cancellationReason}</span></div>}{invoice.returns.length > 0 && <section className="returnHistory"><h3>Return history</h3>{invoice.returns.map((item: any) => <article key={item.id}><span><b>{item.returnNo}</b><small>{new Date(item.createdAt).toLocaleString()} · {item.reason}</small></span><strong>-{money(item.total)}</strong></article>)}</section>}</div><footer><button onClick={() => window.print()}>Print / Reprint</button>{canReturn && <button onClick={startReturn}>Create return</button>}{canCancel && <button className="dangerButton" onClick={startCancel}>Cancel invoice</button>}</footer></aside>;
}

function ReturnDialog({ invoice, close, saved }: any) {
  const [quantities, setQuantities] = useState<Record<string, number>>({}), [reason, setReason] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const items = invoice.items.filter((item: any) => (quantities[item.id] || 0) > 0).map((item: any) => ({ saleItemId: item.id, quantity: quantities[item.id] })); if (!items.length) { setError("Select at least one quantity to return."); return; } setBusy(true); setError(""); try { await apiFetch(`/sales/${invoice.id}/return`, { method: "POST", body: JSON.stringify({ reason, items, requestId: crypto.randomUUID() }) }); await saved(); } catch (issue: any) { setError(issue.message); } finally { setBusy(false); } };
  return <div className="transactionDialog"><form onSubmit={submit}><header><div><small>CONTROLLED RETURN</small><h2>Return items from {invoice.invoice}</h2></div><button type="button" onClick={close}>×</button></header><p>Select only the quantities physically received from the customer. Stock, refund, receivable and accounting entries are updated together.</p><div className="returnLines">{invoice.items.filter((item: any) => item.returnableQuantity > 0).map((item: any) => <label key={item.id}><span><b>{item.product}</b><small>{item.returnableQuantity} available to return</small></span><input type="number" min="0" max={item.returnableQuantity} step="0.001" value={quantities[item.id] || ""} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Number(event.target.value) }))}/></label>)}</div><label className="reasonField">Return reason<textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why these items are being returned"/></label>{error && <div className="formError">{error}</div>}<footer><button type="button" onClick={close}>Keep invoice</button><button className="new" disabled={busy || !reason.trim()}>{busy ? "Processing return…" : "Confirm return"}</button></footer></form></div>;
}

function CancelDialog({ invoice, close, saved }: any) {
  const [reason, setReason] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await apiFetch(`/sales/${invoice.id}/cancel`, { method: "POST", body: JSON.stringify({ reason, requestId: crypto.randomUUID() }) }); await saved(); } catch (issue: any) { setError(issue.message); } finally { setBusy(false); } };
  return <div className="transactionDialog dangerDialog"><form onSubmit={submit}><header><div><small>HIGH-RISK ACTION</small><h2>Cancel {invoice.invoice}?</h2></div><button type="button" onClick={close}>×</button></header><p>The invoice will not be deleted. Stock, customer balance, cash and accounting entries will be reversed with a permanent audit trail.</p><label className="reasonField">Cancellation reason<textarea required rows={4} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="A clear reason is mandatory"/></label>{error && <div className="formError">{error}</div>}<footer><button type="button" onClick={close}>Keep invoice</button><button className="dangerButton" disabled={busy || !reason.trim()}>{busy ? "Cancelling…" : "Cancel and reverse invoice"}</button></footer></form></div>;
}
