CREATE TABLE IF NOT EXISTS tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text UNIQUE NOT NULL,currency_code char(3) NOT NULL DEFAULT 'LKR',timezone text NOT NULL DEFAULT 'Asia/Colombo',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS branches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,code text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,code));
INSERT INTO tenants(name,slug) VALUES('Default Grocery Store','default-grocery') ON CONFLICT(slug) DO NOTHING;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id); ALTER TABLE users ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES branches(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id); ALTER TABLE customers ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id); ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id); ALTER TABLE sales ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id); ALTER TABLE purchases ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);
INSERT INTO branches(tenant_id,name,code) SELECT id,'Main Branch','MAIN' FROM tenants WHERE slug='default-grocery' ON CONFLICT(tenant_id,code) DO NOTHING;
UPDATE users SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery'),branch_id=(SELECT id FROM branches WHERE code='MAIN' LIMIT 1) WHERE tenant_id IS NULL;
UPDATE products SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL; UPDATE customers SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL; UPDATE suppliers SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL; UPDATE sales SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL; UPDATE purchases SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS products_tenant_idx ON products(tenant_id); CREATE INDEX IF NOT EXISTS sales_tenant_idx ON sales(tenant_id,created_at); CREATE INDEX IF NOT EXISTS users_tenant_idx ON users(tenant_id);
