ALTER TABLE categories ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);
UPDATE categories SET tenant_id=(SELECT id FROM tenants WHERE slug='default-grocery') WHERE tenant_id IS NULL;
CREATE TABLE IF NOT EXISTS subcategories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),category_id uuid REFERENCES categories(id),name text NOT NULL,UNIQUE(tenant_id,category_id,name));
CREATE TABLE IF NOT EXISTS brands(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,UNIQUE(tenant_id,name));
CREATE TABLE IF NOT EXISTS units(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,symbol text NOT NULL,UNIQUE(tenant_id,name));
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_code text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS subcategory_id uuid REFERENCES subcategories(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand_id uuid REFERENCES brands(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_id uuid REFERENCES units(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS wholesale_price numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate numeric(6,3) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_expiry boolean NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS archived_at timestamptz;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS products_tenant_code_unique ON products(tenant_id,product_code) WHERE product_code IS NOT NULL AND product_code<>'';
CREATE TABLE IF NOT EXISTS product_price_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,price_type text NOT NULL CHECK(price_type IN('purchase','selling','wholesale')),old_price numeric(14,2) NOT NULL,new_price numeric(14,2) NOT NULL,changed_by uuid REFERENCES users(id),changed_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS product_price_history_product_idx ON product_price_history(product_id,changed_at DESC);
INSERT INTO units(tenant_id,name,symbol) SELECT id,'Piece','pc' FROM tenants ON CONFLICT DO NOTHING;
