CREATE TABLE IF NOT EXISTS purchase_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),branch_id uuid REFERENCES branches(id),po_number text NOT NULL,supplier_id uuid NOT NULL REFERENCES suppliers(id),order_date date NOT NULL DEFAULT current_date,expected_date date,discount numeric(14,2) NOT NULL DEFAULT 0,tax numeric(14,2) NOT NULL DEFAULT 0,total numeric(14,2) NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','approved','ordered','partially_received','completed','cancelled')),notes text,created_by uuid REFERENCES users(id),approved_by uuid REFERENCES users(id),approved_at timestamptz,cancelled_by uuid REFERENCES users(id),cancelled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,po_number));
CREATE TABLE IF NOT EXISTS purchase_order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,product_id uuid NOT NULL REFERENCES products(id),quantity numeric(14,3) NOT NULL CHECK(quantity>0),received_quantity numeric(14,3) NOT NULL DEFAULT 0,unit_cost numeric(14,2) NOT NULL CHECK(unit_cost>=0),discount numeric(14,2) NOT NULL DEFAULT 0,tax numeric(14,2) NOT NULL DEFAULT 0,total numeric(14,2) NOT NULL);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS purchase_order_id uuid REFERENCES purchase_orders(id);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS purchase_date date NOT NULL DEFAULT current_date;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS discount numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS tax numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS payment_method text NOT NULL DEFAULT 'credit';
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'finalized';
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS finalized_by uuid REFERENCES users(id);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS reversed_by uuid REFERENCES users(id);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS reversed_at timestamptz;
ALTER TABLE purchase_items ADD COLUMN IF NOT EXISTS discount numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_items ADD COLUMN IF NOT EXISTS tax numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE purchase_items ADD COLUMN IF NOT EXISTS batch_no text;
CREATE TABLE IF NOT EXISTS purchase_returns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),purchase_id uuid NOT NULL REFERENCES purchases(id),return_number text NOT NULL,supplier_id uuid NOT NULL REFERENCES suppliers(id),return_date date NOT NULL DEFAULT current_date,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','finalized','cancelled')),reason text NOT NULL,total numeric(14,2) NOT NULL DEFAULT 0,created_by uuid REFERENCES users(id),finalized_by uuid REFERENCES users(id),finalized_at timestamptz,cancelled_by uuid REFERENCES users(id),cancelled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,return_number));
CREATE TABLE IF NOT EXISTS purchase_return_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),purchase_return_id uuid NOT NULL REFERENCES purchase_returns(id) ON DELETE CASCADE,purchase_item_id uuid NOT NULL REFERENCES purchase_items(id),product_id uuid NOT NULL REFERENCES products(id),quantity numeric(14,3) NOT NULL CHECK(quantity>0),unit_cost numeric(14,2) NOT NULL,total numeric(14,2) NOT NULL);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES branches(id);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS reference_type text;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS reference_id uuid;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS balance_after numeric(14,3);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES users(id);
UPDATE stock_movements m SET tenant_id=p.tenant_id FROM products p WHERE p.id=m.product_id AND m.tenant_id IS NULL;
CREATE OR REPLACE FUNCTION block_stock_movement_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'stock movement history is immutable; create a reversal adjustment'; END $$;
DROP TRIGGER IF EXISTS stock_movements_immutable ON stock_movements;
CREATE TRIGGER stock_movements_immutable BEFORE UPDATE OR DELETE ON stock_movements FOR EACH ROW EXECUTE FUNCTION block_stock_movement_mutation();
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS approved_by uuid REFERENCES users(id);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS dispatched_at timestamptz;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS received_at timestamptz;
UPDATE stock_transfers t SET tenant_id=b.tenant_id FROM branches b WHERE b.id=t.from_branch_id AND t.tenant_id IS NULL;
UPDATE stock_transfers SET status='received',received_at=COALESCE(received_at,created_at) WHERE status='completed';
ALTER TABLE stock_transfers DROP CONSTRAINT IF EXISTS stock_transfers_status_check;
ALTER TABLE stock_transfers ALTER COLUMN status SET DEFAULT 'draft';
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_status_check CHECK(status IN('draft','approved','dispatched','received','cancelled'));
CREATE TABLE IF NOT EXISTS branch_stock(product_id uuid NOT NULL REFERENCES products(id),branch_id uuid NOT NULL REFERENCES branches(id),quantity numeric(14,3) NOT NULL DEFAULT 0,PRIMARY KEY(product_id,branch_id));
INSERT INTO branch_stock(product_id,branch_id,quantity) SELECT p.id,b.id,p.stock_quantity FROM products p JOIN LATERAL(SELECT id FROM branches WHERE tenant_id=p.tenant_id ORDER BY created_at LIMIT 1)b ON true ON CONFLICT(product_id,branch_id)DO NOTHING;
ALTER TABLE stock_batches ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'available';
ALTER TABLE stock_batches ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE damaged_items ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);
ALTER TABLE damaged_items ADD COLUMN IF NOT EXISTS batch_id uuid REFERENCES stock_batches(id);
ALTER TABLE damaged_items ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE damaged_items ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'finalized';
ALTER TABLE damaged_items ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
UPDATE damaged_items d SET tenant_id=p.tenant_id FROM products p WHERE p.id=d.product_id AND d.tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS stock_movements_history_idx ON stock_movements(tenant_id,product_id,created_at DESC);
CREATE INDEX IF NOT EXISTS purchase_orders_search_idx ON purchase_orders(tenant_id,status,order_date DESC);
INSERT INTO chart_of_accounts(tenant_id,code,name,account_type) SELECT id,'1200','Inventory','asset' FROM tenants ON CONFLICT DO NOTHING;
CREATE OR REPLACE FUNCTION post_procurement_journal() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE inventory_id uuid; payable_id uuid; cash_id uuid; journal_id uuid; direction numeric;
BEGIN
 IF TG_TABLE_NAME='purchases' AND NEW.status IN('finalized','reversed') AND NEW.status IS DISTINCT FROM OLD.status THEN
  direction:=CASE WHEN NEW.status='finalized' THEN 1 ELSE -1 END;
  SELECT id INTO inventory_id FROM chart_of_accounts WHERE tenant_id=NEW.tenant_id AND code='1200';
  SELECT id INTO payable_id FROM chart_of_accounts WHERE tenant_id=NEW.tenant_id AND code='2000';
  SELECT id INTO cash_id FROM chart_of_accounts WHERE tenant_id=NEW.tenant_id AND code='1000';
  INSERT INTO journal_entries(tenant_id,reference_type,reference_id,description,created_by) VALUES(NEW.tenant_id,'purchase',NEW.id,CASE WHEN direction=1 THEN 'GRN finalized ' ELSE 'GRN reversed ' END||NEW.invoice_no,COALESCE(NEW.reversed_by,NEW.finalized_by)) RETURNING id INTO journal_id;
  IF direction=1 THEN
   INSERT INTO journal_lines(journal_id,account_id,debit) VALUES(journal_id,inventory_id,NEW.total);
   IF NEW.total-NEW.paid_amount>0 THEN INSERT INTO journal_lines(journal_id,account_id,credit) VALUES(journal_id,payable_id,NEW.total-NEW.paid_amount); END IF;
   IF NEW.paid_amount>0 THEN INSERT INTO journal_lines(journal_id,account_id,credit) VALUES(journal_id,cash_id,NEW.paid_amount); END IF;
  ELSE
   INSERT INTO journal_lines(journal_id,account_id,credit) VALUES(journal_id,inventory_id,NEW.total);
   IF NEW.total-NEW.paid_amount>0 THEN INSERT INTO journal_lines(journal_id,account_id,debit) VALUES(journal_id,payable_id,NEW.total-NEW.paid_amount); END IF;
   IF NEW.paid_amount>0 THEN INSERT INTO journal_lines(journal_id,account_id,debit) VALUES(journal_id,cash_id,NEW.paid_amount); END IF;
  END IF;
 END IF;
 IF TG_TABLE_NAME='purchase_returns' AND NEW.status='finalized' AND NEW.status IS DISTINCT FROM OLD.status THEN
  SELECT id INTO inventory_id FROM chart_of_accounts WHERE tenant_id=NEW.tenant_id AND code='1200'; SELECT id INTO payable_id FROM chart_of_accounts WHERE tenant_id=NEW.tenant_id AND code='2000';
  INSERT INTO journal_entries(tenant_id,reference_type,reference_id,description,created_by) VALUES(NEW.tenant_id,'purchase_return',NEW.id,'Supplier return '||NEW.return_number,NEW.finalized_by) RETURNING id INTO journal_id;
  INSERT INTO journal_lines(journal_id,account_id,debit) VALUES(journal_id,payable_id,NEW.total); INSERT INTO journal_lines(journal_id,account_id,credit) VALUES(journal_id,inventory_id,NEW.total);
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS purchases_procurement_journal ON purchases;
CREATE TRIGGER purchases_procurement_journal AFTER UPDATE OF status ON purchases FOR EACH ROW EXECUTE FUNCTION post_procurement_journal();
DROP TRIGGER IF EXISTS returns_procurement_journal ON purchase_returns;
CREATE TRIGGER returns_procurement_journal AFTER UPDATE OF status ON purchase_returns FOR EACH ROW EXECUTE FUNCTION post_procurement_journal();
