"use client";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "../components/Sidebar";
import ActionDialog, { type ActionDialogRequest } from "../components/ActionDialog";
import { apiFetch, currentOfflineTransactions, discardOfflineTransaction, reconcileOfflineQueue, retryAllOfflineTransactions, retryOfflineTransaction, type OfflineTransaction, type SyncTransaction } from "../lib/api";
import { useRequireSession } from "../lib/useRequireSession";
import "./sync.css";

export default function SyncPage() {
  useRequireSession();
  const [local, setLocal] = useState<OfflineTransaction[]>([]), [history, setHistory] = useState<SyncTransaction[]>([]);
  const [online, setOnline] = useState(true), [tab, setTab] = useState<"queue" | "history">("queue"), [filter, setFilter] = useState("all");
  const [busy, setBusy] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState(""), [dialog, setDialog] = useState<ActionDialogRequest | null>(null);
  const load = async () => { setLocal(currentOfflineTransactions()); if (!navigator.onLine) return; try { const server = await apiFetch(`/sync-transactions?status=${filter === "all" ? "" : filter}`); reconcileOfflineQueue(server); setHistory(server); setLocal(currentOfflineTransactions()); setError(""); } catch (issue: any) { setError(issue.message); } };
  useEffect(() => { setOnline(navigator.onLine); void load(); const up = () => { setOnline(true); void retryAllOfflineTransactions().finally(load); }, down = () => setOnline(false), changed = () => setLocal(currentOfflineTransactions()); window.addEventListener("online", up); window.addEventListener("offline", down); window.addEventListener("grocerly-offline-queue", changed); return () => { window.removeEventListener("online", up); window.removeEventListener("offline", down); window.removeEventListener("grocerly-offline-queue", changed); }; }, [filter]);
  const counts = useMemo(() => ({ pending: local.filter(x => x.status === "pending" || x.status === "syncing").length, failed: local.filter(x => x.status === "failed").length, conflict: local.filter(x => x.status === "conflict").length, synced: history.filter(x => x.status === "synced").length }), [local, history]);
  const retry = async (id: string) => { setBusy(id); setError(""); try { await retryOfflineTransaction(id); setMessage("Transaction synchronized successfully."); } catch (issue: any) { setError(issue.message); } finally { setBusy(""); await load(); } };
  const retryAll = async () => { setBusy("all"); await retryAllOfflineTransactions(); await load(); setBusy(""); };
  const discard = (item: OfflineTransaction) => setDialog({ title: "Discard offline transaction?", message: "Only discard after confirming that this sale must not be posted. The reason will be recorded in server sync history.", confirmLabel: "Discard transaction", tone: "danger", reasonRequired: true, reasonLabel: "Reason for discarding", onConfirm: async reason => { if (!navigator.onLine) throw new Error("Connect to the server before discarding so the audit reason can be recorded."); await apiFetch(`/sync-transactions/${encodeURIComponent(item.id)}/discard`, { method: "POST", body: JSON.stringify({ reason, terminalId: item.terminalId, localTimestamp: item.createdAt, payload: item.body }) }); discardOfflineTransaction(item.id); setLocal(currentOfflineTransactions()); setMessage("Transaction discarded with an audit record."); } });
  return <main className="shell"><Sidebar active="Offline sync"/><section className="app">
    <header className="topbar"><div><span className="crumb">Administration / Synchronization</span><b>Offline POS control centre</b></div><div className="topbarActions"><button className="ghostButton" onClick={load}>Refresh</button><button className="new" disabled={!online || !local.some(x => x.status !== "conflict") || !!busy} onClick={retryAll}>{busy === "all" ? "Synchronizing…" : "Retry eligible"}</button></div></header>
    <div className="page syncPage"><div className="pageHeading"><div><p>POS RESILIENCE</p><h1>{online ? "Online and monitoring" : "Offline mode active"}</h1><small>Track every terminal attempt, resolve conflicts and prevent duplicate sales across reconnects.</small></div><em className={`financeStatus ${online ? "active" : "inactive"}`}>{online ? "online" : "offline"}</em></div>
      {message && <div className="financeNotice success">{message}<button onClick={() => setMessage("")}>×</button></div>}{error && <div className="financeNotice error">{error}<button onClick={() => setError("")}>×</button></div>}
      <section className="syncMetrics"><article><small>Pending</small><b>{counts.pending}</b></article><article><small>Failed</small><b>{counts.failed}</b></article><article><small>Conflicts</small><b>{counts.conflict}</b></article><article><small>Synced history</small><b>{counts.synced}</b></article></section>
      <div className="workflowTabs"><button className={tab === "queue" ? "active" : ""} onClick={() => setTab("queue")}>This terminal queue <span>{local.length}</span></button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>Server sync history <span>{history.length}</span></button></div>
      {tab === "queue" ? <section className="syncList">{local.map(item => <article key={item.id}><span className={`syncState ${item.status}`}>{item.status}</span><div><b>{item.id}</b><small>{new Date(item.createdAt).toLocaleString()} · Terminal {item.terminalId.slice(0, 8)}</small>{item.lastError && <p>{item.lastError}</p>}{item.nextRetryAt && <small>Automatic retry after {new Date(item.nextRetryAt).toLocaleTimeString()}</small>}</div><strong>{item.attempts} attempts</strong><footer><button disabled={!online || busy === item.id || item.status === "conflict"} onClick={() => retry(item.id)}>{busy === item.id ? "Syncing…" : "Retry"}</button><button className="dangerLink" disabled={!online} onClick={() => discard(item)}>Discard</button></footer></article>)}{!local.length && <div className="emptyState"><b>Terminal queue is clear</b><span>All local transactions have reached the server.</span></div>}</section> : <><section className="syncFilters">{["all", "synced", "failed", "conflict", "discarded", "syncing"].map(value => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value}</button>)}</section><section className="syncList">{history.map(item => <article key={item.id}><span className={`syncState ${item.status}`}>{item.status}</span><div><b>{item.invoice || item.requestId}</b><small>{item.user} · {item.branch || "Default branch"} · Terminal {item.terminalId.slice(0, 12)}</small>{item.lastError && <p>{item.lastError}</p>}{item.resolutionReason && <p>Resolution: {item.resolutionReason}</p>}<small>Last attempt {new Date(item.lastAttemptAt).toLocaleString()}</small></div><strong>{item.attempts} attempts</strong><footer><span>HTTP {item.responseCode || "—"}</span></footer></article>)}{!history.length && <div className="emptyState">No server sync events match this filter.</div>}</section></>}
    </div><ActionDialog request={dialog} close={() => setDialog(null)}/>
  </section></main>;
}
