package main

import (
	"encoding/json"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
	"strings"
	"time"
)

func registerNotifications(m *http.ServeMux, db *pgxpool.Pool) {
	m.HandleFunc("GET /notifications", jsonAPI(authenticated(db, allStaff...)(notifications(db))))
	m.HandleFunc("POST /notifications/read-all", jsonAPI(authenticated(db, allStaff...)(readAllNotifications(db))))
	m.HandleFunc("POST /notifications/{key}/{action}", jsonAPI(authenticated(db, allStaff...)(updateNotification(db))))
	m.HandleFunc("GET /archive", jsonAPI(authenticated(db, "super_admin", "admin")(archiveList(db))))
	m.HandleFunc("POST /archive/{kind}/{id}/restore", jsonAPI(authenticated(db, "super_admin", "admin")(archiveRestore(db))))
	m.HandleFunc("DELETE /archive/{kind}/{id}", jsonAPI(authenticated(db, "super_admin", "admin")(archivePermanentDelete(db))))
}

func notificationQuery() string { return `SELECT n.kind,n.title,n.detail,n.severity,n.entity_id,n.href,n.created_at,COALESCE(s.is_read,false) FROM (
 SELECT CASE WHEN p.stock_quantity<=0 THEN 'out_of_stock' ELSE 'low_stock' END,p.name,p.sku||' · Stock '||p.stock_quantity,CASE WHEN p.stock_quantity<=0 THEN 'critical' ELSE 'warning' END,p.id::text,'/inventory',p.updated_at
 FROM products p LEFT JOIN tenant_settings ts ON ts.tenant_id=p.tenant_id WHERE p.tenant_id=$1 AND p.is_active AND COALESCE(ts.low_stock_enabled,true) AND p.stock_quantity<=p.minimum_stock
 UNION ALL SELECT CASE WHEN b.expiry_date<current_date THEN 'expired' ELSE 'near_expiry' END,p.name,b.batch_no||' · '||b.available_qty||' units · '||b.expiry_date,CASE WHEN b.expiry_date<current_date THEN 'critical' ELSE 'warning' END,b.id::text,'/expiry',b.received_at
 FROM stock_batches b JOIN products p ON p.id=b.product_id LEFT JOIN tenant_settings ts ON ts.tenant_id=p.tenant_id WHERE p.tenant_id=$1 AND b.available_qty>0 AND b.expiry_date<=current_date+COALESCE(ts.expiry_alert_days,30)
 UNION ALL SELECT 'failed_import','Import failed',COALESCE(j.file_name,'Data import')||' · '||j.error_count||' errors','critical',j.id::text,'/data-tools',j.created_at FROM data_import_jobs j WHERE j.tenant_id=$1 AND j.status='failed' AND j.created_at>now()-interval '30 days'
 UNION ALL SELECT 'discount_approval','Discount approval',u.name||' · '||(a.item_discount+a.invoice_discount)::text||' discount','action',a.id::text,'/approvals',a.created_at FROM pos_discount_approvals a JOIN users u ON u.id=a.requested_by WHERE a.tenant_id=$1 AND a.status='pending'
 UNION ALL SELECT 'cheque_approval','Pending cheque',COALESCE(c.name,s.name,'Payment')||' · '||x.amount::text,'action',x.id::text,'/finance',x.created_at FROM (
  SELECT id,tenant_id,customer_id,NULL::uuid supplier_id,amount,received_at created_at FROM customer_payments WHERE clearance_status='pending'
  UNION ALL SELECT id,tenant_id,NULL::uuid,supplier_id,amount,paid_at FROM supplier_payments WHERE clearance_status='pending'
 ) x LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN suppliers s ON s.id=x.supplier_id WHERE x.tenant_id=$1
) n(kind,title,detail,severity,entity_id,href,created_at)
LEFT JOIN user_notification_states s ON s.tenant_id=$1 AND s.user_id=$2 AND s.notification_key=n.kind||':'||n.entity_id
WHERE s.dismissed_at IS NULL ORDER BY CASE n.severity WHEN 'critical' THEN 0 WHEN 'action' THEN 1 ELSE 2 END,n.created_at DESC` }

func notifications(db *pgxpool.Pool) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){ c:=claimsFrom(r);rows,e:=db.Query(r.Context(),notificationQuery(),c.Tenant,c.Sub);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var kind,title,detail,severity,id,href string;var at time.Time;var read bool;if rows.Scan(&kind,&title,&detail,&severity,&id,&href,&at,&read)==nil{out=append(out,map[string]any{"key":kind+":"+id,"kind":kind,"title":title,"detail":detail,"severity":severity,"entityId":id,"href":href,"createdAt":at,"isRead":read})}};json.NewEncoder(w).Encode(out)} }
func updateNotification(db *pgxpool.Pool) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){action:=r.PathValue("action");if action!="read"&&action!="dismiss"{http.Error(w,"invalid notification action",404);return};c:=claimsFrom(r);key:=r.PathValue("key");dismiss:=action=="dismiss";_,e:=db.Exec(r.Context(),`INSERT INTO user_notification_states(tenant_id,user_id,notification_key,is_read,dismissed_at)VALUES($1,$2,$3,true,CASE WHEN $4 THEN now() END)ON CONFLICT(user_id,notification_key)DO UPDATE SET is_read=true,dismissed_at=CASE WHEN $4 THEN now() ELSE user_notification_states.dismissed_at END,updated_at=now()`,c.Tenant,c.Sub,key,dismiss);if e!=nil{http.Error(w,e.Error(),500);return};w.WriteHeader(204)} }
func readAllNotifications(db *pgxpool.Pool) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){c:=claimsFrom(r);rows,e:=db.Query(r.Context(),notificationQuery(),c.Tenant,c.Sub);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();for rows.Next(){var kind,title,detail,severity,id,href string;var at time.Time;var read bool;if rows.Scan(&kind,&title,&detail,&severity,&id,&href,&at,&read)==nil{db.Exec(r.Context(),`INSERT INTO user_notification_states(tenant_id,user_id,notification_key,is_read)VALUES($1,$2,$3,true)ON CONFLICT(user_id,notification_key)DO UPDATE SET is_read=true,updated_at=now()`,c.Tenant,c.Sub,kind+":"+id)}};w.WriteHeader(204)} }

func archiveTable(kind string)(string,bool){switch kind{case "products","users","customers","suppliers":return kind,true};return "",false}
func archiveList(db *pgxpool.Pool)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){kind:=r.URL.Query().Get("kind");table,ok:=archiveTable(kind);if !ok{http.Error(w,"invalid archive type",400);return};q:=strings.TrimSpace(r.URL.Query().Get("q"));c:=claimsFrom(r);var sql string;switch table{case "products":sql=`SELECT id,name,COALESCE(sku,''),COALESCE(barcode,''),COALESCE(archived_at,updated_at) FROM products WHERE tenant_id=$1 AND NOT is_active AND ($2='' OR name ILIKE '%'||$2||'%' OR sku ILIKE '%'||$2||'%' OR barcode ILIKE '%'||$2||'%') ORDER BY archived_at DESC NULLS LAST,name LIMIT 200`;case "users":sql=`SELECT id,name,COALESCE(username,''),email,deleted_at FROM users WHERE tenant_id=$1 AND deleted_at IS NOT NULL AND ($2='' OR name ILIKE '%'||$2||'%' OR username ILIKE '%'||$2||'%' OR email ILIKE '%'||$2||'%') ORDER BY deleted_at DESC,name LIMIT 200`;default:sql=fmt.Sprintf(`SELECT id,name,COALESCE(phone,''),COALESCE(email,''),COALESCE(archived_at,updated_at) FROM %s WHERE tenant_id=$1 AND NOT is_active AND ($2='' OR name ILIKE '%%'||$2||'%%' OR phone ILIKE '%%'||$2||'%%' OR email ILIKE '%%'||$2||'%%') ORDER BY archived_at DESC NULLS LAST,name LIMIT 200`,table)};rows,e:=db.Query(r.Context(),sql,c.Tenant,q);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,name,ref,detail string;var at *time.Time;if rows.Scan(&id,&name,&ref,&detail,&at)==nil{out=append(out,map[string]any{"id":id,"name":name,"reference":ref,"detail":detail,"archivedAt":at})}};json.NewEncoder(w).Encode(out)}}
func archiveRestore(db *pgxpool.Pool)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){table,ok:=archiveTable(r.PathValue("kind"));if !ok{http.Error(w,"invalid archive type",400);return};c:=claimsFrom(r);id:=r.PathValue("id");var sql string;if table=="users"{sql=`UPDATE users SET deleted_at=NULL,deleted_by=NULL,is_active=true WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NOT NULL`}else{sql=fmt.Sprintf(`UPDATE %s SET is_active=true,archived_at=NULL,updated_at=now() WHERE id=$1 AND tenant_id=$2 AND NOT is_active`,table)};tag,e:=db.Exec(r.Context(),sql,id,c.Tenant);if e!=nil||tag.RowsAffected()!=1{http.Error(w,"archived record not found",404);return};auditUserAction(r,db,"ARCHIVE_RESTORED",id,map[string]any{"type":table});w.WriteHeader(204)}}
func archivePermanentDelete(db *pgxpool.Pool)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){table,ok:=archiveTable(r.PathValue("kind"));if !ok{http.Error(w,"invalid archive type",400);return};c:=claimsFrom(r);id:=r.PathValue("id");if id==c.Sub{http.Error(w,"you cannot delete your own account",400);return};condition:="NOT is_active";if table=="users"{condition="deleted_at IS NOT NULL"};tag,e:=db.Exec(r.Context(),fmt.Sprintf(`DELETE FROM %s WHERE id=$1 AND tenant_id=$2 AND %s`,table,condition),id,c.Tenant);if e!=nil{http.Error(w,"permanent delete blocked because this record has business, financial, login, or audit history",409);return};if tag.RowsAffected()!=1{http.Error(w,"archived record not found",404);return};auditUserAction(r,db,"ARCHIVE_PERMANENTLY_DELETED",id,map[string]any{"type":table});json.NewEncoder(w).Encode(map[string]string{"result":"deleted"})}}
