package main

import("bytes";"crypto/sha256";"encoding/hex";"encoding/json";"github.com/jackc/pgx/v5";"github.com/jackc/pgx/v5/pgxpool";"io";"net/http";"strings";"time")
type syncCapture struct{http.ResponseWriter;status int;body bytes.Buffer}
func(s *syncCapture)WriteHeader(code int){s.status=code;s.ResponseWriter.WriteHeader(code)}
func(s *syncCapture)Write(p []byte)(int,error){if s.status==0{s.status=200};s.body.Write(p);return s.ResponseWriter.Write(p)}
func syncPayloadHash(raw []byte)(string,error){var value any;decoder:=json.NewDecoder(bytes.NewReader(raw));decoder.UseNumber();if e:=decoder.Decode(&value);e!=nil{return "",e};canonical,e:=json.Marshal(value);if e!=nil{return "",e};sum:=sha256.Sum256(canonical);return hex.EncodeToString(sum[:]),nil}
func trackPOSSync(db *pgxpool.Pool,next http.HandlerFunc)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){raw,e:=io.ReadAll(http.MaxBytesReader(w,r.Body,2<<20));if e!=nil{http.Error(w,"checkout request is too large",413);return};r.Body=io.NopCloser(bytes.NewReader(raw));var input struct{RequestID string `json:"requestId"`};if json.Unmarshal(raw,&input)!=nil||strings.TrimSpace(input.RequestID)==""{next(w,r);return};fingerprint,e:=syncPayloadHash(raw);if e!=nil{http.Error(w,"invalid checkout payload",400);return};c:=claimsFrom(r);terminal:=strings.TrimSpace(r.Header.Get("X-POS-Terminal"));if terminal==""{terminal="online"};var local *time.Time;if value:=r.Header.Get("X-Local-Timestamp");value!=""{if parsed,err:=time.Parse(time.RFC3339,value);err==nil{local=&parsed}}
	var record string;e=db.QueryRow(r.Context(),`INSERT INTO pos_sync_transactions(tenant_id,request_id,user_id,branch_id,terminal_id,local_timestamp,payload_hash)VALUES($1,$2,$3,NULLIF($4,'')::uuid,$5,$6,$7)ON CONFLICT(tenant_id,request_id)DO UPDATE SET attempts=pos_sync_transactions.attempts+1,last_attempt_at=now(),terminal_id=excluded.terminal_id WHERE pos_sync_transactions.payload_hash=excluded.payload_hash RETURNING id`,c.Tenant,input.RequestID,c.Sub,c.Branch,terminal,local,fingerprint).Scan(&record);if e==pgx.ErrNoRows{_,_=db.Exec(r.Context(),`UPDATE pos_sync_transactions SET status='conflict',last_error='request ID reused with a different sale payload',response_code=409,last_attempt_at=now() WHERE tenant_id=$1 AND request_id=$2`,c.Tenant,input.RequestID);http.Error(w,"sync conflict: transaction ID was reused with different sale details",409);return};if e!=nil{http.Error(w,e.Error(),500);return}
	capture:=&syncCapture{ResponseWriter:w};next(capture,r);status:=capture.status;if status==0{status=200};state:="failed";message:="";invoice:="";if status>=200&&status<300{state="synced";var response map[string]any;if json.Unmarshal(capture.body.Bytes(),&response)==nil{invoice,_=response["invoice"].(string)}}else{message=strings.TrimSpace(capture.body.String());if status==409{state="conflict"}};_,_=db.Exec(r.Context(),`UPDATE pos_sync_transactions SET status=$3,response_code=$4,last_error=NULLIF($5,''),invoice_no=NULLIF($6,''),synced_at=CASE WHEN $3='synced' THEN now() ELSE synced_at END,last_attempt_at=now() WHERE tenant_id=$1 AND request_id=$2`,c.Tenant,input.RequestID,state,status,message,invoice)
}}
func registerSync(m *http.ServeMux,db *pgxpool.Pool){m.HandleFunc("GET /sync-transactions",jsonAPI(authenticated(db,allStaff...)(syncHistory(db))));m.HandleFunc("POST /sync-transactions/{requestID}/discard",jsonAPI(authenticated(db,allStaff...)(discardSyncTransaction(db))))}
func discardSyncTransaction(db *pgxpool.Pool)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){c:=claimsFrom(r);requestID:=strings.TrimSpace(r.PathValue("requestID"));var input struct{Reason,TerminalID,LocalTimestamp,Payload string};if e:=json.NewDecoder(r.Body).Decode(&input);e!=nil||strings.TrimSpace(input.Reason)==""{http.Error(w,"discard reason is required",400);return};fingerprint,e:=syncPayloadHash([]byte(input.Payload));if e!=nil{http.Error(w,"invalid stored transaction payload",400);return};terminal:=strings.TrimSpace(input.TerminalID);if terminal==""{terminal="unknown"};var local *time.Time;if input.LocalTimestamp!=""{if parsed,err:=time.Parse(time.RFC3339,input.LocalTimestamp);err==nil{local=&parsed}};admin:=c.Role=="super_admin"||c.Role=="admin"||c.Role=="manager";tag,e:=db.Exec(r.Context(),`INSERT INTO pos_sync_transactions(tenant_id,request_id,user_id,branch_id,terminal_id,local_timestamp,payload_hash,status,attempts,last_error,response_code,resolution_reason,resolved_by,resolved_at) VALUES($1,$2,$3,NULLIF($4,'')::uuid,$5,$6,$7,'discarded',0,'discarded before synchronization',0,$8,$3,now()) ON CONFLICT(tenant_id,request_id) DO UPDATE SET status='discarded',resolution_reason=$8,resolved_by=$3,resolved_at=now(),last_attempt_at=now() WHERE pos_sync_transactions.status<>'synced' AND (pos_sync_transactions.user_id=$3 OR $9)`,c.Tenant,requestID,c.Sub,c.Branch,terminal,local,fingerprint,strings.TrimSpace(input.Reason),admin);if e!=nil{http.Error(w,e.Error(),500);return};if tag.RowsAffected()==0{http.Error(w,"synced transactions cannot be discarded, or this transaction belongs to another user",409);return};json.NewEncoder(w).Encode(map[string]any{"requestId":requestID,"status":"discarded"})}}
func syncHistory(db *pgxpool.Pool)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){c:=claimsFrom(r);admin:=c.Role=="super_admin"||c.Role=="admin"||c.Role=="manager";rows,e:=db.Query(r.Context(),`SELECT s.id,s.request_id,COALESCE(u.name,'Unknown'),COALESCE(b.name,''),s.terminal_id,s.local_timestamp,s.status,s.attempts,COALESCE(s.last_error,''),COALESCE(s.response_code,0),COALESCE(s.invoice_no,''),s.first_seen_at,s.last_attempt_at,s.synced_at,COALESCE(s.resolution_reason,''),s.resolved_at FROM pos_sync_transactions s LEFT JOIN users u ON u.id=s.user_id LEFT JOIN branches b ON b.id=s.branch_id WHERE s.tenant_id=$1 AND ($2 OR s.user_id=$3) AND ($4='' OR s.status=$4) ORDER BY s.last_attempt_at DESC LIMIT 250`,c.Tenant,admin,c.Sub,r.URL.Query().Get("status"));if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,request,user,branch,terminal,status,lastError,invoice,resolution string;var attempts,code int;var local,synced,resolved *time.Time;var first,last time.Time;if rows.Scan(&id,&request,&user,&branch,&terminal,&local,&status,&attempts,&lastError,&code,&invoice,&first,&last,&synced,&resolution,&resolved)==nil{out=append(out,map[string]any{"id":id,"requestId":request,"user":user,"branch":branch,"terminalId":terminal,"localTimestamp":local,"status":status,"attempts":attempts,"lastError":lastError,"responseCode":code,"invoice":invoice,"firstSeenAt":first,"lastAttemptAt":last,"syncedAt":synced,"resolutionReason":resolution,"resolvedAt":resolved})}};json.NewEncoder(w).Encode(out)}}
