"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import Sidebar from "../components/Sidebar";
import {apiFetch,getSession} from "../lib/api";
import {useRequireSession} from "../lib/useRequireSession";

const groups={Sales:["sales","cashier-sales","product-sales","category-sales","brand-sales","branch-sales","hourly-sales","customer-sales","payment-method-sales","sales-returns","cancelled-sales","discount-analysis","product-profit"],Purchasing:["purchases","product-purchases","purchase-price-variance","purchase-orders","purchase-returns","suppliers","supplier-payments","supplier-ageing"],Inventory:["inventory","branch-stock","stock-valuation-category","batch-stock","low-stock","out-of-stock","slow-moving-stock","expiry","stock-movements","stock-adjustments","damaged-stock","stock-transfers","unit-conversions"],Customers:["customers","customer-ageing","credit-utilization","customer-payments"],Finance:["cash-flow","expenses","trial-balance","profit-loss","comparative-profit-loss","balance-sheet","general-ledger","journal-register"],Operations:["cashier-reconciliation","audit-log","login-history","offline-sync"]} as const;
type Group=keyof typeof groups;
const title=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const iso=(date:Date)=>date.toISOString().slice(0,10);
const descriptions:Record<Group,string>={Sales:"Revenue, invoices, products, cashiers and discount performance.",Purchasing:"Orders, supplier purchases, returns and price movements.",Inventory:"Stock position, valuation, movement, expiry and operational losses.",Customers:"Customer activity, ageing, payments and credit exposure.",Finance:"Cash flow, expenses and core financial statements.",Operations:"Reconciliation, audit history, user access and synchronization."};

export default function Reports(){
 useRequireSession();const router=useRouter(),params=useSearchParams(),requested=params.get("report")||"sales";
 const valid=Object.values(groups).some(items=>(items as readonly string[]).includes(requested));
 const[name,setName]=useState(valid?requested:"sales"),[from,setFrom]=useState(iso(new Date())),[to,setTo]=useState(iso(new Date())),[search,setSearch]=useState("");
 const[report,setReport]=useState<any>({headers:[],rows:[],count:0}),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const activeGroup=useMemo(()=>(Object.entries(groups).find(([,items])=>(items as readonly string[]).includes(name))?.[0]||"Sales") as Group,[name]);
 const load=async()=>{setLoading(true);setError("");try{setReport(await apiFetch(`/reports/${name}?from=${from}&to=${to}&search=${encodeURIComponent(search)}`))}catch(issue:any){setError(issue.message)}finally{setLoading(false)}};
 useEffect(()=>{if(valid)setName(requested)},[requested,valid]);useEffect(()=>{void load()},[name]);
 const choose=(next:string,group=activeGroup)=>{setName(next);router.replace(`/reports?group=${group.toLowerCase()}&report=${next}`,{scroll:false})};
 const chooseGroup=(group:Group)=>choose(groups[group][0],group);
 const setPeriod=(period:"today"|"week"|"month"|"year")=>{const end=new Date(),start=new Date(end);if(period==="week")start.setDate(end.getDate()-6);if(period==="month")start.setDate(1);if(period==="year"){start.setMonth(0);start.setDate(1)}setFrom(iso(start));setTo(iso(end))};
 const exportFile=async(format:"csv"|"xlsx"|"pdf")=>{try{setError("");const session=getSession(),response=await fetch(`/api/reports/${name}?from=${from}&to=${to}&search=${encodeURIComponent(search)}&format=${format}`,{headers:session?.Token?{Authorization:`Bearer ${session.Token}`}:{}});if(!response.ok)throw new Error(await response.text());const url=URL.createObjectURL(await response.blob()),anchor=document.createElement("a");anchor.href=url;anchor.download=`${name}-${from||"all"}-${to||"today"}.${format}`;anchor.click();URL.revokeObjectURL(url)}catch(issue:any){setError(issue.message)}};
 const count=report.count??report.rows?.length??0;
 return <main className="shell"><Sidebar active="Reports"/><section className="app reportsApp"><header className="topbar"><div><span className="crumb">Reports / {activeGroup}</span><b>Business intelligence</b></div><div className="topbarActions reportExports"><button className="ghostButton" onClick={()=>window.print()}>Print</button><button className="ghostButton" onClick={()=>exportFile("pdf")}>PDF</button><button className="ghostButton" onClick={()=>exportFile("csv")}>CSV</button><button className="new" onClick={()=>exportFile("xlsx")}>Excel</button></div></header><div className="page reportsPage reportCentre">
  <div className="pageHeading reportHero"><div><p>REPORTING CENTRE</p><h1>Business reports</h1><small>Choose a category and report, apply a period, then review or export live business data.</small></div><div className="reportHeroStat"><small>SELECTED REPORT</small><b>{title(name)}</b><span>{count} records</span></div></div>
  <nav className="reportGroupNav" aria-label="Report categories">{(Object.keys(groups) as Group[]).map(group=><button key={group} className={activeGroup===group?"active":""} onClick={()=>chooseGroup(group)}><span>{group[0]}</span><div><b>{group}</b><small>{groups[group].length} reports</small></div></button>)}</nav>
  <section className="reportWorkspaceV2"><aside className="reportPicker"><header><small>{activeGroup.toUpperCase()}</small><h2>Choose a report</h2><p>{descriptions[activeGroup]}</p></header><div>{groups[activeGroup].map(item=><button key={item} className={name===item?"active":""} onClick={()=>choose(item)}><span>{title(item)}</span><i>›</i></button>)}</div></aside><div className="reportMain">
   <section className="reportControlCard"><header><div><small>REPORT FILTERS</small><h2>{title(name)}</h2></div><span>Live data</span></header><div className="reportPresetsV2"><button onClick={()=>setPeriod("today")}>Today</button><button onClick={()=>setPeriod("week")}>Last 7 days</button><button onClick={()=>setPeriod("month")}>This month</button><button onClick={()=>setPeriod("year")}>This year</button></div><div className="reportFilterGridV2"><label>From date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="reportSearch">Search<input placeholder="Invoice, party, product or reference" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()}/></label><button className="new" onClick={()=>void load()} disabled={loading}>{loading?"Loading…":"Run report"}</button></div></section>
   {error&&<div className="financeNotice error">{error}<button onClick={()=>setError("")}>×</button></div>}
   <div className="reportSummaryV2"><article><small>Records</small><b>{count}</b><span>matching rows</span></article><article><small>Columns</small><b>{report.headers?.length||0}</b><span>data fields</span></article><article><small>Period</small><b>{from===to?"1 day":"Custom"}</b><span>{from} — {to}</span></article></div>
   <section className="dataCard reportResult reportResultV2"><header><div><p>LIVE RESULT</p><h2>{title(name)}</h2><small>{from||"All dates"} to {to||"Today"}</small></div><span className="countBadge">{count} records</span></header>{loading?<div className="reportLoading"><span/><b>Preparing report…</b></div>:<div className="tableScroll"><table><thead><tr>{report.headers?.map((item:string)=><th key={item}>{item}</th>)}</tr></thead><tbody>{report.rows?.map((row:string[],index:number)=><tr key={index}>{row.map((value,cell)=><td key={cell}>{value}</td>)}</tr>)}</tbody></table></div>}{!loading&&!report.rows?.length&&<div className="emptyState"><b>No matching records</b><span>Try a wider date range or clear the search field.</span></div>}</section>
  </div></section>
 </div></section></main>
}
