"use client";

import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Sidebar from "../components/Sidebar";
import ActionDialog,{type ActionDialogRequest} from "../components/ActionDialog";
import {apiFetch,can} from "../lib/api";
import {useRequireSession} from "../lib/useRequireSession";
import { money } from "../lib/format";

type Batch={id:string;product:string;sku:string;barcode:string;batchNo:string;expiry:string;available:number;unitCost:number;stockValue:number;batchStatus:string;expiryState:string;branch:string;invoice:string;supplier:string;receivedAt:string;notes:string;canEdit:boolean};
type Summary={valid:number;nearExpiry:number;expired:number;noExpiry:number;removed:number;atRiskQuantity:number;atRiskValue:number};
const emptySummary:Summary={valid:0,nearExpiry:0,expired:0,noExpiry:0,removed:0,atRiskQuantity:0,atRiskValue:0};

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dateText=(value:string)=>value?new Date(`${value}T00:00:00`).toLocaleDateString("en-LK"):"Not tracked";

export default function ExpiryManagement(){
 useRequireSession();
 const router=useRouter();
 const[view,setView]=useState<"batches"|"history">("batches"),[rows,setRows]=useState<Batch[]>([]),[history,setHistory]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]);
 const[summary,setSummary]=useState<Summary>(emptySummary),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const[filters,setFilters]=useState({q:"",status:"all",branchId:"",from:"",to:"",days:"30",limit:"25"}),[applied,setApplied]=useState(filters),[editing,setEditing]=useState<Batch|null>(null),[dialog,setDialog]=useState<ActionDialogRequest|null>(null);
 const load=async()=>{setLoading(true);setMessage("");try{if(view==="history"){setHistory(await apiFetch(`/expiry/history?q=${encodeURIComponent(applied.q)}`));return}const query=new URLSearchParams({...applied,page:String(page)});const data=await apiFetch(`/expiry/batches?${query}`);setRows(data.rows||[]);setSummary(data.summary||emptySummary);setTotal(data.total||0)}catch(e:any){setMessage(e.message)}finally{setLoading(false)}};
 useEffect(()=>{apiFetch("/inventory/branches").then(setBranches).catch(()=>setBranches([]))},[]);
 useEffect(()=>{void load()},[view,applied,page]);
 const apply=(event:React.FormEvent)=>{event.preventDefault();setPage(1);setApplied({...filters})};
 const remove=(batch:Batch)=>setDialog({title:`Remove expired ${batch.product}?`,message:`This removes ${batch.available} units from batch ${batch.batchNo||"General"} and creates permanent stock and accounting entries.`,confirmLabel:"Remove expired stock",tone:"danger",reasonRequired:true,reasonLabel:"Removal reason",onConfirm:async(reason)=>{await apiFetch(`/expiry/batches/${batch.id}/remove`,{method:"POST",body:JSON.stringify({reason,requestId:crypto.randomUUID()})});setMessage("Expired stock removed and recorded successfully.");await load()}});
 const exportCSV=()=>{const cells=["Product,SKU,Barcode,Batch,Expiry,Status,Available,Unit cost,Stock value,Branch,Supplier,Invoice",...rows.map(x=>[x.product,x.sku,x.barcode,x.batchNo,x.expiry,label(x.expiryState),x.available,x.unitCost,x.stockValue,x.branch,x.supplier,x.invoice].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))];const url=URL.createObjectURL(new Blob([cells.join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="expiry-batches.csv";a.click();URL.revokeObjectURL(url)};
 const pages=Math.max(1,Math.ceil(total/Number(applied.limit||25)));
 return <main className="shell"><Sidebar active="Expiry management"/><section className="app"><header className="topbar"><div><span className="crumb">Inventory / Expiry</span><b>Expiry management</b></div><div className="expiryTopActions"><button className="ghostButton" onClick={exportCSV} disabled={!rows.length}>Export CSV</button><button className="new" onClick={()=>router.push("/procurement")}>+ Receive stock / GRN</button></div></header><div className="page expiryPage">
  <div className="pageHeading"><div><p>BATCH-WISE STOCK CONTROL</p><h1>Expiry management</h1><small>Expiry dates enter through GRN. Expired quantities are removed through an immutable stock and accounting adjustment.</small></div></div>
  <div className="expirySummary">
   <SummaryCard title="Expired now" value={summary.expired} tone="danger" onClick={()=>{setFilters(x=>({...x,status:"expired"}));setApplied(x=>({...x,status:"expired"}));setPage(1)}}/>
   <SummaryCard title={`Near expiry (${applied.days} days)`} value={summary.nearExpiry} tone="warning" onClick={()=>{setFilters(x=>({...x,status:"near_expiry"}));setApplied(x=>({...x,status:"near_expiry"}));setPage(1)}}/>
   <SummaryCard title="Valid batches" value={summary.valid} tone="success" onClick={()=>{setFilters(x=>({...x,status:"valid"}));setApplied(x=>({...x,status:"valid"}));setPage(1)}}/>
   <SummaryCard title="At-risk quantity" value={summary.atRiskQuantity} subtitle={money(summary.atRiskValue)} tone="info"/>
   <SummaryCard title="Removed / depleted" value={summary.removed} tone="neutral" onClick={()=>{setFilters(x=>({...x,status:"removed"}));setApplied(x=>({...x,status:"removed"}));setPage(1)}}/>
  </div>
  <nav className="workflowTabs expiryViews"><button className={view==="batches"?"active":""} onClick={()=>setView("batches")}>Batch register</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}>Removal history</button></nav>
  {message&&<button className="catalogMessage" onClick={()=>setMessage("")}>{message}<span>×</span></button>}
  <form className="expiryFilters" onSubmit={apply}><label>Search<input value={filters.q} onChange={e=>setFilters(x=>({...x,q:e.target.value}))} placeholder="Product, SKU, barcode or batch"/></label><label>Status<select value={filters.status} onChange={e=>setFilters(x=>({...x,status:e.target.value}))}><option value="all">All batches</option><option value="expired">Expired now</option><option value="near_expiry">Near expiry</option><option value="valid">Valid</option><option value="no_expiry">No expiry date</option><option value="removed">Removed</option><option value="depleted">Depleted / returned</option></select></label><label>Branch<select value={filters.branchId} onChange={e=>setFilters(x=>({...x,branchId:e.target.value}))}><option value="">All branches</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>From<input type="date" value={filters.from} onChange={e=>setFilters(x=>({...x,from:e.target.value}))}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters(x=>({...x,to:e.target.value}))}/></label><label>Alert days<input type="number" min="1" max="365" value={filters.days} onChange={e=>setFilters(x=>({...x,days:e.target.value}))}/></label><button className="new">Apply filters</button></form>
  {view==="batches"?<section className="workflowRecords expiryTable"><header><div><h2>Batch register</h2><small>{loading?"Loading…":`${total} matching batches`}</small></div><button onClick={()=>window.print()}>Print</button></header><div className="tableScroll"><table><thead><tr><th>Product</th><th>Batch / Source</th><th>Expiry</th><th>Available</th><th>Stock value</th><th>Branch</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.product}</b><small>{x.sku}{x.barcode&&` · ${x.barcode}`}</small></td><td><b>{x.batchNo||"No batch number"}</b><small>{x.supplier||"—"}{x.invoice&&` · ${x.invoice}`}</small></td><td><b>{dateText(x.expiry)}</b><small>{remaining(x.expiry)}</small></td><td>{x.available}</td><td>{money(x.stockValue)}</td><td>{x.branch||"Unassigned"}</td><td><span className={`status expiry-${x.expiryState}`}>{label(x.expiryState)}</span></td><td><div className="recordActions">{can("expiry.edit")&&x.canEdit&&<button onClick={()=>setEditing(x)}>Correct details</button>}{can("expiry.edit")&&x.expiryState==="expired"&&x.available>0&&<button className="dangerAction" onClick={()=>remove(x)}>Remove stock</button>}</div></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<div className="emptyState">No batches match these filters. Receive expiry-tracked stock through a GRN to create batch records.</div>}<footer className="expiryPagination"><label>Rows<select value={filters.limit} onChange={e=>{setFilters(x=>({...x,limit:e.target.value}));setApplied(x=>({...x,limit:e.target.value}));setPage(1)}}><option>25</option><option>50</option><option>100</option></select></label><span>Page {page} of {pages}</span><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Previous</button><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)}>Next</button></footer></section>:<History rows={history} loading={loading}/>} 
  {editing&&<EditBatch batch={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);setMessage("Batch details corrected. The reason was added to the audit trail.");await load()}}/>}<ActionDialog request={dialog} close={()=>setDialog(null)}/>
 </div></section></main>
}

function SummaryCard({title,value,subtitle,tone,onClick}:any){return <button type="button" className={`expiryStat ${tone}`} onClick={onClick} disabled={!onClick}><span>{title}</span><b>{Number(value||0).toLocaleString("en-LK")}</b>{subtitle&&<small>{subtitle}</small>}</button>}
function remaining(value:string){if(!value)return "Expiry not tracked";const days=Math.ceil((new Date(`${value}T00:00:00`).getTime()-new Date(new Date().toDateString()).getTime())/86400000);return days<0?`${Math.abs(days)} day(s) overdue`:days===0?"Expires today":`${days} day(s) remaining`}
function History({rows,loading}:any){return <section className="workflowRecords expiryTable"><header><div><h2>Expired-stock removal history</h2><small>{loading?"Loading…":`${rows.length} permanent records`}</small></div><button onClick={()=>window.print()}>Print</button></header><div className="tableScroll"><table><thead><tr><th>Product</th><th>Batch</th><th>Quantity removed</th><th>Reason</th><th>User</th><th>Date / time</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><b>{x.product}</b><small>{x.sku}</small></td><td>{x.batchNo||"—"}</td><td className="negativeQty">{x.quantity}</td><td>{x.reason}</td><td>{x.user}</td><td>{new Date(x.createdAt).toLocaleString("en-LK")}</td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<div className="emptyState">No expired-stock removals recorded.</div>}</section>}
function EditBatch({batch,close,saved}:any){const[value,setValue]=useState({batchNo:batch.batchNo,expiryDate:batch.expiry,notes:batch.notes,reason:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await apiFetch(`/expiry/batches/${batch.id}`,{method:"PUT",body:JSON.stringify(value)});await saved()}catch(x:any){setError(x.message);setBusy(false)}};return <div className="workflowModal expiryModal" role="dialog" aria-modal="true"><form onSubmit={submit}><div className="formTitle"><div><h2>Correct batch details</h2><small>{batch.product} · Changes are audit logged.</small></div><button type="button" className="quietButton" onClick={close}>Close</button></div><label>Batch number<input required value={value.batchNo} onChange={e=>setValue(x=>({...x,batchNo:e.target.value}))}/></label><label>Expiry date<input required type="date" value={value.expiryDate} onChange={e=>setValue(x=>({...x,expiryDate:e.target.value}))}/></label><label>Notes<textarea rows={3} value={value.notes} onChange={e=>setValue(x=>({...x,notes:e.target.value}))}/></label><label>Correction reason<input required placeholder="Why is this being changed?" value={value.reason} onChange={e=>setValue(x=>({...x,reason:e.target.value}))}/></label>{error&&<div className="formError">{error}</div>}<button className="new" disabled={busy}>{busy?"Saving…":"Save correction"}</button></form></div>}
